version: "3"

volumes:
  mariadb_data:
    driver: local


networks:
  go-net:
    driver: bridge

services:
  gin-webcore:
    build:
      context: ./
    volumes:
      - .:/go/src/gin-webcore
    ports:
      - "1002:1002"
    depends_on:
      - mariadb
      - phpmyadmin
    networks:
      - go-net

  # go-core:
  #   build:
  #     context: ./
  #   volumes:
  #     - .:/go/src/go-core
  #   ports:
  #     - "1001:1001"
  #   depends_on:
  #     - mariadb
  #     - phpmyadmin
  #   networks:
  #     - go-net

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - go-net

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - go-net

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
    networks:
      - go-net

  redis-webui:
    image: erikdubbelboer/phpredisadmin
    environment:
      # 服務器主機
      REDIS_1_HOST: redis
      # 服務器名稱
      REDIS_1_NAME: gin-webcore
      # 服務器PORT
      REDIS_1_PORT: 6379
      # 設定帳號密碼
      ADMIN_USER: root
      ADMIN_PASS: 123456
    networks:
      - go-net
    ports:
      - '8081:80'
    depends_on:
      - redis

