definitions:
  adminaccesses.AdminAccessModel:
    properties:
      code:
        example: test
        type: string
      enable:
        type: integer
      name:
        example: test
        type: string
    required:
    - code
    - name
    type: object
  adminlevels.AdminLevelModel:
    properties:
      enable:
        type: integer
      level:
        example: 2
        type: integer
      name:
        example: test
        type: string
    required:
    - level
    - name
    type: object
  auth.Login:
    properties:
      account:
        example: admin
        type: string
      password:
        example: qaz123
        type: string
    required:
    - account
    - password
    type: object
  response.response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: localhost:1002
info:
  contact: {}
  description: This is a Gin-webcore
  license: {}
  title: Golang Gin-Webcore API
  version: "1.0"
paths:
  /admin-accesses/:
    get:
      consumes:
      - application/json
      description: GET Admin Access List
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: SortColumn
        in: query
        name: sortColumn
        type: string
      - description: SortDirection
        in: query
        name: sortDirection
        type: string
      - description: Name
        in: query
        name: name
        type: string
      - description: Enable
        in: query
        name: enable
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Access List
      tags:
      - AdminAccesses
    post:
      consumes:
      - application/json
      description: GET Admin Access Create
      parameters:
      - description: Admin Access Create
        in: body
        name: data
        schema:
          $ref: '#/definitions/adminaccesses.AdminAccessModel'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Access Create
      tags:
      - AdminAccesses
  /admin-accesses/{id}:
    delete:
      consumes:
      - application/json
      description: DELETE Admin Access Delete
      parameters:
      - description: Admin Access ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Access Delete
      tags:
      - AdminAccesses
    patch:
      consumes:
      - application/json
      description: PATCH Admin Access Update
      parameters:
      - description: Admin Access ID
        in: path
        name: id
        type: integer
      - description: Admin Access Update
        in: body
        name: data
        schema:
          $ref: '#/definitions/adminaccesses.AdminAccessModel'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Access Update
      tags:
      - AdminAccesses
  /admin-accesses/view/{id}:
    get:
      consumes:
      - application/json
      description: GET Admin Access View
      parameters:
      - description: Admin Access ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Access View
      tags:
      - AdminAccesses
  /admin-levels/:
    get:
      consumes:
      - application/json
      description: GET Admin Levels List
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: SortColumn
        in: query
        name: sortColumn
        type: string
      - description: SortDirection
        in: query
        name: sortDirection
        type: string
      - description: Name
        in: query
        name: name
        type: string
      - description: Enable
        in: query
        name: enable
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Levels List
      tags:
      - AdminLevels
    post:
      consumes:
      - application/json
      description: GET Admin Level Create
      parameters:
      - description: Admin Level Create
        in: body
        name: data
        schema:
          $ref: '#/definitions/adminlevels.AdminLevelModel'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Level Create
      tags:
      - AdminLevels
  /admin-levels/{id}:
    delete:
      consumes:
      - application/json
      description: GET Admin Level Delete
      parameters:
      - description: Admin Level ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Level Delete
      tags:
      - AdminLevels
    get:
      consumes:
      - application/json
      description: GET Admin Level View
      parameters:
      - description: Admin Level ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Level View
      tags:
      - AdminLevels
    patch:
      consumes:
      - application/json
      description: GET Admin Level Update
      parameters:
      - description: Admin Level ID
        in: path
        name: id
        type: integer
      - description: Admin Level Update
        in: body
        name: data
        schema:
          $ref: '#/definitions/adminlevels.AdminLevelModel'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Level Update
      tags:
      - AdminLevels
  /auth/info:
    get:
      description: Get Admin Info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Info
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Admin Login
      parameters:
      - description: login
        in: body
        name: data
        schema:
          $ref: '#/definitions/auth.Login'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin Login
      tags:
      - Auth
  /auth/sidebarMenu:
    get:
      description: Get SidebarMenu
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.response'
      summary: Admin SidebarMenu
      tags:
      - Auth
swagger: "2.0"
